#!/usr/bin/env zsh

_aup() {
  __aup
}

__aup() {
  _arguments \
    {--verbose,--no-verbose}'[turns verbose output]' \
    {--debug,--no-debug}'[turns debugging output]' \
    {--silent,--no-silent}'[tell autoproj to not display anything]' \
    {--color,--no-color}'[enables or disables colored display (enabled by default if the terminal supports it)]' \
    {--progress,--no-progress}'[enables or disables progress display (enabled by default if the terminal supports it)]' \
    {--keep-going,--no-keep-going,-k}'[do not stop on build or checkout errors]' \
    {--config,--no-config}'[(do not) update configuration. The default is to update configuration if explicitely selected or if no additional arguments are given on the command line, and to not do it if packages are explicitely selected on the command line]' \
    {--bundler,--no-bundler}'[(do not) update bundler. This is automatically enabled only if no arguments are given on the command line]' \
    {--autoproj,--no-autoproj}'[(do not) update autoproj. This is automatically enabled only if no arguments are given on the command line]' \
    {--osdeps,--no-osdeps}'[enable or disable osdeps handling]' \
    --from'[use this existing autoproj installation to check out the packages (for importers that support this)]' \
    {--checkout-only,--no-checkout-only,-c}'[only checkout packages, do not update existing ones]' \
    {--local,--no-local}'[use only local information for the update (for importers that support it)]' \
    {--osdeps-filter-uptodate,--no-osdeps-filter-uptodate}'[controls whether the osdeps subsystem should filter up-to-date packages or not]' \
    {--deps,--no-deps}'[whether the package dependencies should be recursively updated (the default) or not. -n is a shortcut for --no-deps]' \
    {--reset,--no-reset}'[forcefully resets the repository to the state expected by autoproj''s configuration]' \
    {--force-reset,--no-force-reset}'[like --reset, but bypasses tests that ensure you won''t lose data]' \
    --retry-count'[force the importer''s retry count to this value]' \
    {--parallel,-p}'[maximum number of parallel jobs]' \
    --mainline'[compare to the given baseline. if ''true'', the comparison will ignore any override, otherwise it will take into account overrides only up to the given package set]' \
    {--auto-exclude,--no-auto-exclude}'[if true, packages that fail to import will be excluded from the build]' \
    '*:arg:_autoproj_installed_packages'
}


compdef _aup aup
